### PR TITLE
Various uwap-home changes

### PR DESCRIPTION
**Pull request by Ranlvor**

### CODE REVIEW

**Comment by uwap** [comment]
Please rework the pull request to be compatible with the new icon changes. See https://github.com/uwap/mqtt-control-map/wiki/Icons for more information

**Comment by Ranlvor** [comment]
Rework is done, Travis is green. https://travis-ci.org/github/uwap/mqtt-control-map/builds/736626853

**Comment by Ranlvor** [comment]
Now the linter says 

```  192:27  error    'Buffer' is not defined  no-undef```

What do I need to import to be able to use buffer? I need buffer because the type-function of a command-topic has to return a buffer, not a string, for flow to allow it.

**Comment by Ranlvor** [comment]
Thank you for the import @uwap. The Tests are now green again. 

https://travis-ci.org/github/uwap/mqtt-control-map/builds/743691721

**Comment by Ranlvor** [comment]
The import Buffer did not work too well. Flow and Webpack and yarn lint are fine with it, but I get „TypeError: Cannot read property 'from' of undefined“ whenever I try to use the command in the browser. When I remove the import sending commands via browser works but the linter complains:
```
  193:27  error    'Buffer' is not defined  no-undef
  205:27  error    'Buffer' is not defined  no-undef
```

**Pull request closed without merging**
